#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Learner-account cloud foundation"

stage "Create the Frankfurt Supabase project"
say "Create the hosted project that will own learner accounts and learning-progress snapshots."
open_url "https://supabase.com/dashboard"
step "Select New project and create a project in the Frankfurt EU region. Choose and save a strong database password."
step "After creation, copy the project ref from the dashboard URL: https://supabase.com/dashboard/project/<project-ref>."
ask SUPABASE_PROJECT_REF "Paste the Supabase project ref:"
ask_secret SUPABASE_DB_PASSWORD "Paste the database password (kept only in memory for this run):"
pause "Project created and values entered. Press Enter to continue."

stage "Link and apply the learning-progress migration"
say "The CLI will authenticate you, link this repository to the new project, preview the migration, then apply it only after confirmation."
step "A browser may open for Supabase CLI login. Complete it with the same Supabase account that owns the project."
npx supabase login
step "Linking to project $SUPABASE_PROJECT_REF."
SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase link --project-ref "$SUPABASE_PROJECT_REF"
step "Previewing the version-controlled migration; no remote data changes are made by this preview."
SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase db push --dry-run
if confirm "Apply the previewed migration to project $SUPABASE_PROJECT_REF?"; then
  SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase db push
else
  SKIPPED+=("database migration (re-run this wizard when ready to apply it)")
  warn "migration not applied"
fi

stage "Configure Supabase Auth"
say "Set the public URL and passwordless-email settings for the GitHub Pages study app."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF"
step "Open Authentication → URL Configuration. Set Site URL to https://bimurto.github.io/driving-theory/."
step "Add https://bimurto.github.io/driving-theory/ and http://127.0.0.1:3000 to Redirect URLs."
step "Open Authentication → Providers (or Sign In / Providers) → Email. Keep email sign-up and passwordless email enabled."
step "Set one-time-password length to 6 and expiry to 3600 seconds. Keep CAPTCHA disabled for this release."
step "Open Authentication → Rate Limits and set email-code limits appropriate for launch; 30 new users per hour is the standard custom-SMTP default."
pause "Auth URL, email OTP, CAPTCHA, and rate-limit settings configured. Press Enter to continue."

stage "Verify bimurto.io with Resend"
say "Resend must verify the sending domain before it can deliver sign-in codes from auth@bimurto.io."
open_url "https://resend.com/domains"
step "Add the domain bimurto.io. Copy every required SPF and DKIM DNS record into the DNS provider for bimurto.io."
step "Return to Resend and wait until the domain status is Verified. Do not continue while it is pending or failed."
pause "bimurto.io is verified in Resend. Press Enter to continue."

stage "Connect Resend SMTP to Supabase Auth"
say "Create an SMTP credential in Resend and paste it directly into Supabase. The credential is never saved by this wizard."
open_url "https://resend.com/api-keys"
step "Create an API key for Supabase Auth and copy it. Treat it as a secret."
pause "API key copied. Press Enter to open the Supabase project."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF"
step "Open Authentication → Emails → SMTP Settings and enable Custom SMTP."
step "Enter host smtp.resend.com, port 465, username resend, and the Resend API key as the password."
step "Set the sender address to auth@bimurto.io, save, and confirm the SMTP configuration is enabled."
note "Do not put the Resend API key, Supabase secret key, service-role key, or database password in GitHub, browser code, or this repository."
pause "Custom SMTP configured. Press Enter to finish."

finish
